language: ruby
rvm:
  - 2.2

dist: trusty
sudo: false

branches:
  only:
    - poc

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules # NPM packages

addons:
  #ssh_known_hosts: s210904.gridserver.com
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # - graphicsmagick
      - g++-4.8

env:
  CXX=g++-4.8

before_install:
  - nvm install 6
  - npm install gulp-cli -g
  - npm install git+https://git@github.com/gulpjs/gulp.git#4.0 --save-dev
  - npm install yarn -g
  - yarn

script: gulp build --prod

before_deploy:
  - openssl aes-256-cbc -K $encrypted_b9977dca951b_key -iv $encrypted_b9977dca951b_iv -in deploy_key.enc -out /tmp/deploy_key -d
  #- openssl aes-256-cbc -K $encrypted_f55b475b43f3_key -iv $encrypted_f55b475b43f3_iv -in deploy_keys.tar.enc -out /tmp/deploy_keys.tar -d
  #- tar -xvf /tmp/deploy_keys.tar -C /tmp/
  #- mv /tmp/rsync-credentials.json rsync-credentials.json
  #- eval "$(ssh-agent -s)"
  #- chmod 600 /tmp/id_rsa
  #- ssh-add /tmp/id_rsa
  
chmod 600 /tmp/deploy_key
eval `ssh-agent -s`
ssh-add /tmp/deploy_key

deploy:
  provider: script
  skip_cleanup: true
  script: gulp deploy
  on:
    branch: poc

after_deploy:
  # See https://github.com/travis-ci/travis-ci/issues/8082#issuecomment-315151953
  - ssh-agent -k
